# This program prints Hello, world! 
print(" ------------------------------------------------")
print("|                                                |")
print("|    04GoodbyeWorld                              |")
print("|    Name : Erin Seo                             |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello World")
input ("------> Program paused - press enter to continue")
print("Goodbye World")